name: Coverage

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  coverage:
    name: 📊 Coverage & Summary
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'all-contributors/') && !startsWith(github.event.pull_request.title, 'docs:')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[watchmedo]' -r requirements-tests.txt

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=watchdog --cov-report=term-missing --cov-report=xml:coverage.xml --junitxml=pytest.xml

      - name: Python Coverage Comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@a05be3d2e8a6272d3ef5fb2840ab20368bb2eb71 # v4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MINIMUM_GREEN: 70
          MINIMUM_ORANGE: 50
          ANNOTATE_MISSING_LINES: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
